project:
    analysers:
        enabled:
            - *
        disabled:
            -
    directories:
        include:
            - 'src'
            - 'tests'
        exclude:
            - 'vendor'
