name: PHP Composer

on: [push]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v1
            -   name: PHPCodeSniffer
                uses: rtCamp/action-phpcs-inspection@v1.0.0
            -   name: PHP Insights Action
                uses: stefanzweifel/phpinsights-action@v1.0.0
            -   name: EditorConfig-Action
                uses: zbeekman/EditorConfig-Action@v1.1.1
            -   name: PHPUnit (php-actions)
                uses: php-actions/phpunit@v1.0.0
